[package]
name = "doppio-cli"
description = "Command-line interface for the doppio Ledger compiler. Provides the `dop` binary."
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file = "../../LICENSE"
keywords.workspace = true
categories.workspace = true
default-run = "dop"

[[bin]]
name = "dop"
path = "src/main.rs"

[dependencies]
doppio = { path = "../doppio", version = "1.0.0" }

# CLI-specific deps not used by the library:
chrono = { workspace = true }
clap = { workspace = true }
regex = { workspace = true }
rust_decimal = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
